Examples of suspend_chains
dwavesystems/minorminer pull request #81
Opened 2019-05-01 23:17 UTC by joseppinilla

Just thought it would be useful to have.
But also, wanted to point out that, since the internal pins are also returned in the embedding, a naive use of the embedding with the drawing capabilities, will cause an error if show_labels=True is used.

Maybe there's nothing to do here but the user should be aware of this. Or maybe the drawing package should handle it... or... networkx shouldn't use label keys to address the pos dictionary, which is what causes the error.

2019-05-03 16:13 UTC, arcondello approved these changes

2019-05-03 16:13 UTC, arcondello requested changes
I like the example, but we should add a test to CI so that we know it doesn't get out of date.

2019-05-03 20:55 UTC, boothby commented
> But also, wanted to point out that, since the internal pins are also returned in the embedding

Uhhh... can you rephrase that in the form of a bug report?  Because that's awful and we shouldn't be returning those.  I'll have time to fix that late next week

2019-06-13 23:10 UTC, boothby commented
I've added these examples as tests in response to @arcondello's change request.

2019-06-14 18:35 UTC, boothby commented
I've submitted a pull request to @joseppinilla's repo removing the note about the bug resolved in #88.  @arcondello's changes are resolved and I'm happy with this example (provided that note is removed).

2019-06-14 18:37 UTC, boothby requested changes
Strike lines 28-30 (accepting my PR to @joseppinilla's repo)

2019-06-17 21:51 UTC, boothby approved these changes

2019-06-18 18:32 UTC, arcondello approved these changes

2019-06-18 18:36 UTC, merged